name: Build Project

on: [push, pull_request]

jobs:
  build:
    name: Run full lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Run go test
        run: go test -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
